# Patterned after https://github.com/Moerill/Mess/blob/master/.github/workflows/release.yml

name: Release

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        run: zip -@ release.zip < release/zip_list
      - name: Report
        run: unzip -l release.zip
